#!groovy

// Generated by IBM TransformationAdvisor
// Thu Jan 24 10:11:17 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresorts10war'
    mvnCommands = '--version'
    test='false'
}